export const SET_REGISTER_MOBILE_NUMBER = 'SET_REGISTER_MOBILE_NUMBER';

export const VALIDATE_USER = 'VALIDATE_USER';
export const VALIDATE_USER_SUCCESS = 'VALIDATE_USER_SUCCESS';
export const VALIDATE_USER_FAILURE = 'VALIDATE_USER_FAILURE';

export const SUBMIT_LOGIN_OTP = 'SUBMIT_LOGIN_OTP';
export const SUBMIT_LOGIN_OTP_SUCCESS = 'SUBMIT_LOGIN_OTP_SUCCESS';
export const SUBMIT_LOGIN_OTP_FAILURE = 'SUBMIT_LOGIN_OTP_FAILURE';
